/**
 * @file Add command — installs a registry item into the consumer project.
 *
 * Triggered by `shared-packages add <item-name>`. Copies each declared source
 * file from the registry to the consumer's project directory at the configured
 * target path, then optionally installs npm dependencies.
 *
 * Requires a `pixelthread.json` in the consumer project root (generated by
 * `shared-packages init`). The file defines path mappings that resolve
 * `${pathKey}` templates in item targets.
 *
 * ## Safety
 *
 * - Validates that all target paths stay within the consumer project directory
 *   (path-traversal prevention).
 * - Skips existing files unless `--overwrite` is passed.
 * - Checks that every declared source file actually exists in the registry
 *   before copying.
 */

import fs from 'fs-extra';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { getPackageRoot } from '../registry/index';
import type { ConsumerConfig, Registry, RegistryItem } from '../types/index';
import { detectPackageManager } from '../utils/index';
import { resolveTarget } from '../utils/consumer-config';
import { transformImports } from '../utils/transform-imports';

const execFileAsync = promisify(execFile);

/** Options that control how the add command behaves. */
export type AddOptions = {
  /**
   * Overwrite existing target files without warning.
   *
   * When `false` (default), files that already exist at the target path are
   * skipped and a warning is printed. When `true`, they are silently replaced.
   */
  overwrite?: boolean;

  /**
   * Skip automatic dependency installation.
   *
   * When `true`, the CLI will not run `npm install` / `pnpm add` etc. for
   * the item's declared `dependencies`. Useful for dry-runs or CI environments.
   */
  skipInstall?: boolean;
};

/**
 * Installs a registry item — and its item dependencies — into the current project.
 *
 * Resolves `itemDependencies` recursively, deduplicates, and resolves `${pathKey}`
 * target templates using the consumer's `pixelthread.json`.
 *
 * @param item - The registry item to install.
 * @param config - Consumer config for path-key resolution.
 * @param registry - The full registry (used to resolve itemDependencies).
 * @param options - Behaviour flags (overwrite, skipInstall).
 * @param installed - Internal set tracking already-installed items (prevents loops).
 *
 * @throws If a `${pathKey}` target references an unknown path key.
 * @throws If a declared source file is missing in the registry.
 * @throws If a target path attempts to escape the consumer project directory.
 */
export async function addItem(
  item: RegistryItem,
  config: ConsumerConfig,
  registry: Registry,
  options: AddOptions,
  installed?: Set<string>,
): Promise<void> {
  const seen = installed ?? new Set<string>();

  if (seen.has(item.name)) {
    return;
  }
  seen.add(item.name);

  // Resolve item dependencies first (breadth-first, depth-limit checked by `seen`).
  if (item.itemDependencies?.length) {
    for (const depName of item.itemDependencies) {
      const dep = registry.items.find((i) => i.name === depName);
      if (!dep) {
        console.warn(`Warning: itemDependency "${depName}" not found in registry — skipping.`);
        continue;
      }
      await addItem(dep, config, registry, options, seen);
    }
  }

  const packageRoot = getPackageRoot();
  const projectRoot = process.cwd();

  for (const file of item.files) {
    const resolvedTarget = resolveTarget(file.target, config);
    const sourcePath = path.join(packageRoot, file.source);
    const targetPath = path.resolve(projectRoot, resolvedTarget);

    if (!targetPath.startsWith(`${projectRoot}${path.sep}`)) {
      throw new Error(
        `Invalid target path: ${resolvedTarget}. Path escapes the project directory.`,
      );
    }

    if (!(await fs.pathExists(sourcePath))) {
      throw new Error(
        `Registry source file is missing: ${file.source}. ` +
          `Verify the file exists in the registry package.`,
      );
    }

    if ((await fs.pathExists(targetPath)) && !options.overwrite) {
      console.warn(`Skipped ${resolvedTarget}: it already exists. Use --overwrite to replace it.`);
      continue;
    }

    await fs.ensureDir(path.dirname(targetPath));

    const content = await fs.readFile(sourcePath, 'utf8');
    const transformed = transformImports(content, config);
    await fs.writeFile(targetPath, transformed, 'utf8');

    console.log(`Added ${resolvedTarget}`);
  }

  if (!options.skipInstall && item.dependencies?.length) {
    const packageManager = await detectPackageManager(projectRoot);

    console.log(`Installing dependencies with ${packageManager}: ${item.dependencies.join(', ')}`);

    await execFileAsync(packageManager, ['add', ...item.dependencies], {
      cwd: projectRoot,
    });
  }
}
